### PR TITLE
Add commands to provide github, twitter and facebook links

### PR DESCRIPTION
**Pull request by pkill37**
Thought about this a few minutes ago and decided to do it really quick. Could be useful. Maybe.

Why not? :)

### CODE REVIEW

**Comment by JordanMussi** [comment]
You could make an extra config array at the top, and be able to add your own from that.
But what you have here can easily be replicated, so the above point is useless.

**Comment by DennisTT** [comment]
Thanks Fabio.  Could you also add the commands to the help message before I merge in the commit?

**Comment by pkill37** [comment]
Yeah I realized that after sending the pull request.

I also thought it would be nice to do something more with !github. Since IRC is a place for developers to chat, it would be nice to be able to link to pull requests, repos and issues in an easy manner like !github mybb-resources pull 12.

I'm gonna work on that and add the commits as soon as I can.

**Comment by pkill37** [comment]
There we go. I've added the command to the help message and developed it a bit more like I indicated before.

Clearly it doesn't check if the repository, pull request or issue exists. But I don't think it's worth checking anyway. I assume this is only useful if you're referencing an issue you're already aware of.

I've also added to the bottom an object with the links since I was repeating them quite a bit, as well as a generic error message I was using (may be useful to others?). Let me know if that's okay.

**Comment by DennisTT** [comment]
Merged. Thanks

**Pull request merged**
